import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
    container: {
        width: '100%',
        alignItems: 'center',
        backgroundColor: '#DFEDEB',
        flex: 1,
    },
    scrollview: {
        backgroundColor: '#DFEDEB',
        width: '100%',
        alignItems: 'center',
        flex: 1,
    },
    button: {
        backgroundColor: "#B30000",
        width: "90%",
        borderRadius: 5,
        padding: "4%",
        alignItems: "center",
        marginTop: "5%",
        borderColor: "#B1B1B1",
        borderWidth: 1,
        boxShadowColor: "#000",
        boxShadowOffset: {
            width: 0,
            height: 2,
        },
        boxShadowOpacity: .25,
        boxShadowRadius: 3.84,
        elevation: 1,
        marginBottom: "3%",
    },
    buttonText: {
        color: "white",
        fontSize: 18,
    },
    containerField: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#FEFEFE",
        padding: "2%",
        marginVertical: "2%",
        paddingHorizontal: "5%",
        boxShadowColor: "#000",
        boxShadowOffset: {
            width: 0,
            height: 2,
        },
        boxShadowOpacity: .25,
        boxShadowRadius: 3.84,
        elevation: 1,
    },
    titleField: {
        fontSize: 16,
        fontWeight: "bold",
        fontFamily: "sans-serif-light",
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        fontFamily: "sans-serif-light",
        color: "#FEFEFE",
        marginBottom: "5%",
    },
    centeredView: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: 'rgba(0, 0, 0, 0.89)',
    },
    modalView: {
        margin: 20,
        backgroundColor: "#086972",
        borderRadius: 20,
        padding: "5%",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2
        },
        width: "86%",
    },
    modalText: {
        fontFamily: 'sans-serif-light',
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFF',
        textAlign: 'center',
        marginBottom: "5%",
    },
    textStyle: {
        fontFamily: 'sans-serif-light',
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFF',
        textAlign: 'center',
    },
    modalButton: {
        backgroundColor: 'rgba(0, 160, 0, 1)',
        borderRadius: 10,
        padding: "3%",
        marginTop: "4%",
        alignItems: 'center',
        width: "100%",
    },
    backModal: {
        marginTop: "4%",
        alignItems: 'center',
    },
    modalInput: {
        width: "100%",
        backgroundColor: "#FFF",
        borderRadius: 5,
        padding: "3%",
        marginBottom: "5%",
    },
})